# Generated by Django 5.1.2 on 2024-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_exercise_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories',
            field=models.FloatField(),
        ),
    ]
