# Generated by Django 5.1.2 on 2024-11-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='demonstration_video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='demonstration_video_2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
