# Generated by Django 5.1.2 on 2024-11-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_exercise_demonstration_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='additional_fitness_goal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
