# Generated by Django 5.1.2 on 2024-11-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_userprofile_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='additional_fitness_goal',
            new_name='additional_fitness_goals',
        ),
    ]
