# Generated by Django 5.1.2 on 2024-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_additional_fitness_goal_userprofile_additional_fitness_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='equipment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='musle_group',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
