# Generated by Django 5.1.2 on 2024-11-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_workout_equipment_workout_musle_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='duration_minutes',
        ),
    ]
