# Generated by Django 5.1.2 on 2024-11-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_workout_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
