# Generated by Django 5.1.2 on 2024-12-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_workout_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desired_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type_of_food',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
