# Generated by Django 5.1.2 on 2024-12-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_userprofile_desired_weight_userprofile_type_of_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='additional_fitness_goals',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
