# Generated by Django 5.1.2 on 2024-12-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_userprofile_additional_fitness_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='arm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hips',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leg_in_thigh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='waist',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
