# Generated by Django 5.1.2 on 2024-12-14 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_userprofile_arm_userprofile_chest_userprofile_hips_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(max_length=500)),
                ('protein_per_100g', models.FloatField()),
                ('fat_per_100g', models.FloatField()),
                ('carb_per_100g', models.FloatField()),
                ('kcal_per_100g', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=500)),
                ('preparation_time', models.CharField(max_length=500)),
                ('number_of_portions', models.IntegerField()),
                ('weight_portion', models.CharField(max_length=500)),
                ('kcal_per_100g', models.FloatField()),
                ('protein_per_100g', models.FloatField()),
                ('fat_per_100g', models.FloatField()),
                ('carb_per_100g', models.FloatField()),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mealgroups')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=500)),
                ('gramming', models.IntegerField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='CookingSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='UserFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramming_product', models.IntegerField()),
                ('kcal', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('carb', models.FloatField()),
                ('meal_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mealgroups')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='meal_groups',
            field=models.ManyToManyField(through='base.UserFood', to='base.mealgroups'),
        ),
    ]
