# Generated by Django 5.1.2 on 2024-12-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_group_id_recipes_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookingsteps',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
