# Generated by Django 5.1.2 on 2024-12-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_recipe_id_cookingsteps_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='gramming',
            field=models.CharField(max_length=500),
        ),
    ]
