# Generated by Django 5.1.2 on 2024-12-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_ingredients_gramming'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfood',
            name='water',
            field=models.IntegerField(null=True),
        ),
    ]
