# Generated by Django 5.1.2 on 2024-12-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_targetnutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetnutrition',
            name='target_water',
            field=models.IntegerField(),
        ),
    ]
