# Generated by Django 5.1.2 on 2024-12-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_targetnutrition_target_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetnutrition',
            name='target_water',
            field=models.FloatField(),
        ),
    ]
